http_server:
  address: "0.0.0.0:23199"
  timeout: 4s
  idle_timeout: 30s
  

postgres:
  db_name: heimdallr
  db_user: heimdallr
  db_pass: postgres
  db_host: localhost
  db_port: 5432
  db_ssl_mode: "disable"

broker:
  